dist: xenial
notifications:
  email: false
git:
  quiet: true
  depth: 1
language: java
jdk: openjdk8
python: 3
service:
  - docker
addons:
  apt:
    update: true
    packages:
      - jq
      - curl
      - sudo
      - lsof
      - wget
      - bash
      - docker-ce
      - python3-dev
      - python3-pip
      - python3-six
      - python3-setuptools
install: true
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip >/dev/null >/dev/null 2>&1
  - pip install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
  - http --version --debug
  - docker-compose -v
  #
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8001 8002 8080 5432 27017
before_script:
  - ./mvnw docker:start
  - wait_for 27017
  - ./mvnw
  - java -jar target/*.jar &
  - wait_for 8080
script:
  - http :8080/actuator/health | jq '.'
  - http :8080 | jq '.'
  - http :8080/actuator/info | jq '.'
after_script:
  - stop_any 80 8080
  - ./mvnw spring-boot:build-info package >/dev/null
  - java -jar target/*.jar &
  - wait_for 8080
  - http :8080/actuator/info | jq '.'
  - ./mvnw docker:stop >/dev/null
  - stop_any 80 8080 27017
cache:
  packages: true
  pip: true
  directories:
    - ~/.m2
    - ~/.local
    - ~/.docker
env:
  global:
    secure: dqPm1hDCSGVVnXmd2xaxsoHcdOC1c0hbcsau59WjH4hOj6hx+fonHuzgwWfX+mEdqJv/Wtiw6eHAPdKgDmvNw6Ifm1mER5SeKPR/PREsTMrYCmsvomqq5YofwY9m9dtVfOZOvWOBuv60rOEILKeUtQrai2qfqikkFnIx76aFy/2tLOXHZ/LSWh/TdkXulZGpBzVK/sQYLBGao9GY4aBhGYGBQtVpPccyIMlH60/eX/J7ITQtyl/JjJ6obI1haGg+N5fpVyse9FhVSulJ0RTZtPOxXYJdNwLiexxc+NmgQog/sYnqlNLM+3n04b7HAvhxSQyc9aBcE0VliRxAXqtSUARNCvb7M/kk9aC8Hu/fDzVyaxC9L4jPDUrpRx+9r0OVKUyi6/67Yr1T8k4XKY8sFnVNZxxmn1AQSLmrQVdIg0p7tJR4rkCvm9NCnC5egpt1662k8QvHx8e9kRMDBY+btInjl7y0NKQUQih6Hcxn+KWpnQ4/RiTAyKXDkGkkuKPtxZ1ViVrGlM4EBoMvvRgoRGJQwlIBAdTLLyhFnq4OLgUzHh1PS2rO/5H8y7J+ch/G7Owtwo9CzuFBYFOBj/PJe0ryxAG97e+Or9np4xaevgUV+iXYN4WbvSEfbmv8E9OGbj+y0ZqHU51mGJOCtLr9Ap7fHmEYg3fM1NNfauTaZQg=
